- name: start mariadb
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes   

- name: Create a new database with name bobdata
  community.mysql.mysql_db:
    name: bobdata
    state: present
    login_user: ansible
    login_password: new_password

- name: Create database user with name 'bob' and password '12345' with all database privileges
  community.mysql.mysql_user:
    name: bob
    password: 12345
    priv: '*.*:ALL'
    state: present 
    login_user: ansible
    login_password: new_password
    
   
    